### ISSUE TITLE
Mark as valid uppercase letters

### ISSUE THREAD

**Issue by azapg** [unnamed/unnamed.team#1]
Change regex to accept uppercase letters
https://github.com/unnamed/unnamed.team/blob/31be509c0460a0dd15ef76078b8128d63f27f376/src/pages/project/glyphs.tsx#L21

**Comment by yusshu** [comment]
Minecraft resource pack keys (like `minecraft:textures/emoji/emojiname.png`) don't accept uppercase characters, so we can't allow emoji names to use them
