### ISSUE TITLE
1-14 character limit

### ISSUE THREAD

**Issue by syrupderg** [unnamed/unnamed.team#2]
leave the 14 character limit for emojis, i know its for auto complete feature but simply dont have auto complete feature for emojis that has more than 14 characters.
https://github.com/unnamed/unnamed.team/blob/31be509c0460a0dd15ef76078b8128d63f27f376/src/pages/project/glyphs.tsx#L21

**Comment by xenitzys** [comment]
this will probably ruin the autocompletion feature and throw an exception when they are longer than 14 characters because it is not designed for emojis to be longer than 14 characters

**Comment by cumhilo** [comment]
I don't think this can be considered a issue, it is simply not designed this way intentionally because it is not allowed, also, just mentioning the regex expression is not correct, since modifying only this will not work

**Comment by syrupderg** [comment]
> I don't think this can be considered a issue, it is simply not designed this way intentionally because it is not allowed, also, just mentioning the regex expression is not correct, since modifying only this will not work

well make it allow more than 14 characters then, so default discord emojis could work. just because you added auto complete feature doesn't mean it should always enabled for all emojis. simply disable auto complete feature for emojis that has more that 16 characters. as for regex yup it also has to be fixed from plugin side too but i couldn't find the file

**Comment by OcZi** [comment]
A warning in console should be placed to not support cases where the emoji's length is greater than 14

**Comment by yusshu** [comment]
Closed by #3
